variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  DOCKER_DRIVER: overlay2
  # MySQL
  MYSQL_USER: app
  MYSQL_PASSWORD: mySecretPassword
  MYSQL_ROOT_PASSWORD: mySecretPassword
  MYSQL_DATABASE: app
  MYSQL_HOST: mysql:3306
  # PostgreSQL
  POSTGRES_USER: app
  POSTGRES_PASSWORD: mySecretPassword
  POSTGRES_DB: app
  POSTGRES_HOST: postgres:5432
  #MsSQL
  SA_PASSWORD: myStrong(!)Password
  ACCEPT_EULA: Y
  MSSQL_USER: sa
  MSSQL_PASSWORD: myStrong(!)Password
  MSSQL_DATABASE: msdb
  MSSQL_HOST: microsoft__mssql-server-linux:1433

stages:
  - build
  - package
  - security

.build: &build
  stage: build
  image: maven:3-jdk-8-alpine
  script:
    - export profile=$( echo ${CI_JOB_NAME} | awk '{print $2}' )
    - mvn $MAVEN_CLI_OPTS install -Drevision=$CI_COMMIT_REF_SLUG-${profile} -P${profile}
    - cat target/site/jacoco/index.html
  coverage: '/Total.*?([0-9]{1,3})\s?%/'
  artifacts:
    paths:
      - target/*.jar
      - target/site/jacoco
      - target/cucumber-html-reports
      - target/surefire-reports/*.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    expire_in: 5 days
  cache:
    key: build-java
    paths:
      - .m2/repository

.package: &package
  stage: package
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - export profile=$( echo ${CI_JOB_NAME} | awk '{print $2}' )
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${profile} .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${profile}
  only:
    - master
    - tags

build h2:
  <<: *build

build mysql:
  <<: *build
  services:
    - mysql

build mariadb:
  <<: *build
  services:
    - name: mariadb
      alias: mysql

build postgresql:
  <<: *build
  services:
    - postgres:alpine

build mssql:
  <<: *build
  services:
    - microsoft/mssql-server-linux

package h2:
  <<: *package
  dependencies:
    - build h2

package mysql:
  <<: *package
  dependencies:
    - build mysql

package mariadb:
  <<: *package
  dependencies:
    - build mariadb

package postgresql:
  <<: *package
  dependencies:
    - build postgresql

package mssql:
  <<: *package
  dependencies:
    - build mssql

code_quality:
  stage: security
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - >
      docker run --env SOURCE_CODE="$PWD" \
        --volume "$PWD":/code \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  dependencies: []
  artifacts:
    paths: [gl-code-quality-report.json]
  only:
    - branches
  except:
    variables:
      - $CODE_QUALITY_DISABLED

sast:
  stage: security
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - >
      docker run --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}" \
        --volume "$PWD:/code" \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  dependencies: []
  artifacts:
    reports:
      sast: gl-sast-report.json

dependency_scanning:
  stage: security
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - >
      docker run --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}" \
        --volume "$PWD:/code" \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  dependencies: []
  artifacts:
    paths: [ gl-dependency-scanning-report.json ]
  only:
    - master

container_scanning:
  stage: security
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker run -d --name db arminc/clair-db:latest
    - docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
    - apk add -U wget ca-certificates
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-h2
    - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    - mv clair-scanner_linux_amd64 clair-scanner
    - chmod +x clair-scanner
    - touch clair-whitelist.yml
    - retries=0
    - echo "Waiting for clair daemon to start"
    - while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
    - ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-h2 || true
  dependencies: []
  artifacts:
    paths: [gl-container-scanning-report.json]
  only:
    - master

license_management:
  stage: security
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/license-management:$CI_SERVER_VERSION_MAJOR-$CI_SERVER_VERSION_MINOR-stable"
    entrypoint: [""]
  script:
    - /run.sh analyze .
  artifacts:
    reports:
      license_management: gl-license-management-report.json
